node{
     
    stage('SCM Checkout'){
        git url: 'https://github.com/Divyasyamala9491/DivyaDemoRepo.git',branch: 'main'
    }
  
    
    stage('Build Docker Image'){
        sh 'docker build -t karthikeyinid/webelight_practical_test .'
    }
    
    stage('Push Docker Image'){
        withCredentials([string(credentialsId: 'Divya', variable: 'Docker_Hub_Pwd')]) {
          sh "docker login -u Divya111 -p ${Kashik@143}"
        }
        sh 'docker push karthikeyinid/webelight_practical_test'
     }
     
      stage('Run Docker Image '){
        
        def dockerRun = ' docker run  -d -p 5050:5050 --name webelight_practical_test karthikeyinid/webelight_practical_test'
        
       }
       
    }
     
     
}
